### ISSUE TITLE
Uable to run on windows

### ISSUE THREAD

**Issue by ondrovic** [ipsjolly/react--table-tutorial-app#2]
using the default project on running an npm i on windows I get the following

> npm ERR! code 1
> npm ERR! path C:\users\me\Desktop\react--table-tutorial-app\node_modules\node-sass
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
> npm ERR! Building: C:\Program Files\nodejs\node.exe C:\users\me\Desktop\react--table-tutorial-app\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp verb cli [
> npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
> npm ERR! gyp verb cli   'C:\\users\\me\\Desktop\\react--table-tutorial-app\\node_modules\\node-gyp\\bin\\node-gyp.js',
> npm ERR! gyp verb cli   'rebuild',
> npm ERR! gyp verb cli   '--verbose',
> npm ERR! gyp verb cli   '--libsass_ext=',
> npm ERR! gyp verb cli   '--libsass_cflags=',
> npm ERR! gyp verb cli   '--libsass_ldflags=',
> npm ERR! gyp verb cli   '--libsass_library='
> npm ERR! gyp verb cli ]
> npm ERR! gyp info using node-gyp@3.8.0
> npm ERR! gyp info using node@16.9.1 | win32 | x64
> npm ERR! gyp verb command rebuild []
> npm ERR! gyp verb command clean []
> npm ERR! gyp verb clean removing "build" directory
> npm ERR! gyp verb command configure []
> npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
> npm ERR! gyp verb `which` failed Error: not found: python2
> npm ERR! gyp verb `which` failed     at getNotFoundError (C:\users\me\Desktop\react--table-tutorial-app\node_modules\which\which.js:13:12)
> npm ERR! gyp verb `which` failed     at F (C:\users\me\Desktop\react--table-tutorial-app\node_modules\which\which.js:68:19)
> npm ERR! gyp verb `which` failed     at E (C:\users\me\Desktop\react--table-tutorial-app\node_modules\which\which.js:80:29)
> npm ERR! gyp verb `which` failed     at C:\users\me\Desktop\react--table-tutorial-app\node_modules\which\which.js:89:16
> npm ERR! gyp verb `which` failed     at C:\users\me\Desktop\react--table-tutorial-app\node_modules\isexe\index.js:42:5
> npm ERR! gyp verb `which` failed     at C:\users\me\Desktop\react--table-tutorial-app\node_modules\isexe\windows.js:36:5
> npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
> npm ERR! gyp verb `which` failed  python2 Error: not found: python2
> npm ERR! gyp verb `which` failed     at getNotFoundError (C:\users\me\Desktop\react--table-tutorial-app\node_modules\which\which.js:13:12)
> npm ERR! gyp verb `which` failed     at F (C:\users\me\Desktop\react--table-tutorial-app\node_modules\which\which.js:68:19)
> npm ERR! gyp verb `which` failed     at E (C:\users\me\Desktop\react--table-tutorial-app\node_modules\which\which.js:80:29)
> npm ERR! gyp verb `which` failed     at C:\users\me\Desktop\react--table-tutorial-app\node_modules\which\which.js:89:16
> npm ERR! gyp verb `which` failed     at C:\users\me\Desktop\react--table-tutorial-app\node_modules\isexe\index.js:42:5
> npm ERR! gyp verb `which` failed     at C:\users\me\Desktop\react--table-tutorial-app\node_modules\isexe\windows.js:36:5
> npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
> npm ERR! gyp verb `which` failed   code: 'ENOENT'
> npm ERR! gyp verb `which` failed }
> npm ERR! gyp verb check python checking for Python executable "python" in the PATH
> npm ERR! gyp verb `which` succeeded python C:\Python39\python.EXE
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.vernpm ERR! gyp ERR! stack                       ^
> npm ERR! gyp ERR! stack SyntaxError: invalid syntax
> npm ERR! gyp ERR! stack
> npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)       
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
> npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
> npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
> npm ERR! gyp ERR! System Windows_NT 10.0.19043
> npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\users\\me\\Desktopocess:301:5)\\react--table-tutorial-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="         \\react--table-tutori
> npm ERR! gyp ERR! cwd C:\users\me\Desktop\react--table-tutorial-app\node_modules\node-s--libsass_cflags=" "-ass
> npm ERR! gyp ERR! node -v v16.9.1                                                         ass
> npm ERR! gyp ERR! node-gyp -v v3.8.0
> npm ERR! gyp ERR! not ok
> npm ERR! Build failed with error code: 1

**Comment by rahul-cubastion** [comment]
try npm i --force
